# Generated by Django 4.1.6 on 2025-02-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='document_key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
